permalink: /:year:month/:title
markdown: redcarpet
redcarpet:
  extensions: [autolink, fenced_code_blocks, no_intra_emphasis, smart, strikethrough, superscript, tables]
pygments: true
exclude:
        - Rakefile
        - Makefile
        - media
